In [2]:
# Team 1 LendingClub primary notebook
# import dependencies
import pandas as pd
import numpy as np # needed for replace nan code below
import glob

# pull in all csvs and merge them into a single dataframe
bigdf = pd.concat([pd.read_csv(f, low_memory=False) for f in
                    glob.glob('data/LoanStats*.csv')], ignore_index=True)

In [3]:
# drop irrelevant rows
data = bigdf.drop([
                "id", "member_id", "url", "desc", "hardship_type", "hardship_reason",
                "hardship_status", "deferral_term", "hardship_amount",
                "hardship_start_date", "hardship_end_date", "payment_plan_start_date",
                "hardship_length", "hardship_dpd", "hardship_loan_status",
                "orig_projected_additional_accrued_interest",
                "hardship_payoff_balance_amount", "hardship_last_payment_amount",
                "debt_settlement_flag_date", "settlement_status", "settlement_date",
                "settlement_amount", "settlement_percentage", "settlement_term","grade",\
                "sub_grade","emp_title","debt_settlement_flag","disbursement_method","verification_status",\
                "url","desc","zip_code","earliest_cr_line","inq_last_6mths","mths_since_last_record",\
                "pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv",\
                "total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","recoveries","collection_recovery_fee",\
                "last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med",\
                "policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq",\
                "tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il",\
                "total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi",\
                "total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths",\
                "delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc",\
                "mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd",\
                "num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0",\
                "num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75",\
                "pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit",\
                "revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util",\
                "sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med",\
                "sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term",\
                "hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd",\
                "hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount",\
                "disbursement_method","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount",\
                "settlement_percentage","settlement_term","mths_since_last_major_derog"], axis=1)

In [4]:
data.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,emp_length,home_ownership,annual_inc,issue_d,loan_status,pymnt_plan,purpose,title,addr_state,dti,delinq_2yrs,mths_since_last_delinq,open_acc,total_rec_late_fee
0,30000.0,30000.0,30000.0,36 months,7.34%,930.99,3 years,OWN,95000.0,Mar-18,Fully Paid,n,house,Home buying,TX,16.18,1.0,10.0,10.0,0.0
1,34825.0,34825.0,34825.0,60 months,12.61%,785.45,2 years,MORTGAGE,125000.0,Mar-18,Current,n,credit_card,Credit card refinancing,AZ,21.31,0.0,45.0,12.0,0.0
2,2600.0,2600.0,2600.0,36 months,7.96%,81.43,3 years,MORTGAGE,62000.0,Mar-18,Current,n,other,Other,MI,19.61,0.0,NaN,8.0,0.0
3,20000.0,20000.0,20000.0,60 months,9.92%,424.16,3 years,MORTGAGE,110000.0,Mar-18,Current,n,home_improvement,Home improvement,VA,10.56,0.0,44.0,9.0,0.0
4,17000.0,17000.0,17000.0,60 months,20.39%,454.10,10+ years,RENT,52000.0,Mar-18,Current,n,debt_consolidation,Debt consolidation,FL,15.65,0.0,77.0,9.0,0.0

In [10]:
mydf= pd.read_csv('T Part/VIX.csv')
mydf.head()

    issue_d       Open       High    Low      Close  Adj Close  Volume
0  1/1/2018  10.950000  15.420000   8.92  13.540000  13.540000       0
1  2/1/2018  13.050000  50.299999  12.50  19.850000  19.850000       0
2  3/1/2018  19.959999  26.219999  13.31  19.969999  19.969999       0
3  4/1/2018  21.070000  25.719999  14.57  15.930000  15.930000       0
4  5/1/2018  16.000000  18.780001  10.91  15.430000  15.430000       0

In [23]:
merged_df = data.merge(mydf,how = "outer", left_on = "issue_d", right_on=)
merged_df

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,emp_length,home_ownership,annual_inc,issue_d,...,delinq_2yrs,mths_since_last_delinq,open_acc,total_rec_late_fee,Open,High,Low,Close,Adj Close,Volume
0,30000.0,30000.0,30000.0,36 months,7.34%,930.99,3 years,OWN,95000.0,Mar-18,...,1.0,10.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,34825.0,34825.0,34825.0,60 months,12.61%,785.45,2 years,MORTGAGE,125000.0,Mar-18,...,0.0,45.0,12.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2600.0,2600.0,2600.0,36 months,7.96%,81.43,3 years,MORTGAGE,62000.0,Mar-18,...,0.0,NaN,8.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,20000.0,20000.0,20000.0,60 months,9.92%,424.16,3 years,MORTGAGE,110000.0,Mar-18,...,0.0,44.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,17000.0,17000.0,17000.0,60 months,20.39%,454.10,10+ years,RENT,52000.0,Mar-18,...,0.0,77.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
5,5000.0,5000.0,5000.0,36 months,20.39%,186.82,8 years,RENT,50000.0,Mar-18,...,1.0,9.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
6,20000.0,20000.0,20000.0,36 months,10.41%,649.21,NaN,MORTGAGE,19000.0,Mar-18,...,0.0,NaN,6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7,19200.0,19200.0,19200.0,60 months,17.47%,482.04,5 years,RENT,36500.0,Mar-18,...,3.0,15.0,14.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8,15000.0,15000.0,15000.0,36 months,9.92%,483.45,2 years,OWN,196000.0,Mar-18,...,0.0,65.0,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
9,6500.0,6500.0,6500.0,36 months,6.07%,197.95,10+ years,MORTGAGE,50000.0,Mar-18,...,0.0,58.0,7.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10,6000.0,6000.0,6000.0,36 months,10.41%,194.77,1 year,RENT,46000.0,Mar-18,...,0.0,NaN,11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
11,3000.0,3000.0,3000.0,36 months,7.34%,93.10,9 years,RENT,52000.0,Mar-18,...,0.0,26.0,7.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
12,1000.0,1000.0,1000.0,36 months,17.47%,35.89,2 years,RENT,51000.0,Mar-18,...,0.0,61.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
13,3200.0,3200.0,3200.0,36 months,7.96%,100.22,1 year,RENT,42000.0,Mar-18,...,0.0,NaN,8.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
14,3000.0,3000.0,3000.0,36 months,11.98%,99.62,10+ years,OWN,52000.0,Mar-18,...,0.0,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
15,25000.0,25000.0,25000.0,60 months,9.92%,530.20,10+ years,MORTGAGE,120000.0,Mar-18,...,1.0,21.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
16,17000.0,17000.0,17000.0,36 months,10.90%,555.76,10+ years,OWN,70000.0,Mar-18,...,0.0,NaN,6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
17,34000.0,34000.0,34000.0,60 months,10.41%,729.28,2 years,RENT,105000.0,Mar-18,...,0.0,NaN,18.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
18,12000.0,12000.0,12000.0,36 months,6.07%,365.45,10+ years,MORTGAGE,240000.0,Mar-18,...,0.0,47.0,14.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
19,6025.0,6025.0,6025.0,36 months,9.43%,192.81,3 years,RENT,39000.0,Mar-18,...,0.0,30.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
20,3000.0,3000.0,3000.0,36 months,9.43%,96.01,10+ years,RENT,97000.0,Mar-18,...,0.0,33.0,6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
21,24000.0,24000.0,24000.0,36 months,13.58%,815.38,< 1 year,MORTGAGE,73620.0,Mar-18,...,1.0,15.0,18.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
22,10000.0,10000.0,10000.0,36 months,9.43%,320.01,10+ years,MORTGAGE,65000.0,Mar-18,...,0.0,35.0,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
23,20000.0,20000.0,20000.0,60 months,26.77%,607.97,3 years,RENT,33500.0,Mar-18,...,0.0,NaN,27.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
24,12000.0,12000.0,12000.0,60 months,16.01%,291.89,10+ years,MORTGAGE,110000.0,Mar-18,...,0.0,NaN,14.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
25,2500.0,2500.0,2500.0,36 months,6.71%,76.87,10+ years,MORTGAGE,53700.0,Mar-18,...,0.0,NaN,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
26,25000.0,25000.0,25000.0,60 months,12.61%,563.85,10+ years,RENT,78000.0,Mar-18,...,0.0,NaN,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
27,12000.0,12000.0,12000.0,36 months,10.41%,389.53,5 years,MORTGAGE,110000.0,Mar-18,...,0.0,25.0,12.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
28,20000.0,20000.0,20000.0,36 months,9.43%,640.01,3 years,RENT,48000.0,Mar-18,...,0.0,NaN,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
29,25000.0,25000.0,25000.0,60 months,14.07%,582.62,3 years,MORTGAGE,35000.0,Mar-18,...,0.0,NaN,8.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495241,24000.0,24000.0,24000.0,36 months,19.92%,890.95,10+ years,RENT,34000.0,Oct-18,...,0.0,NaN,12.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495242,20000.0,20000.0,20000.0,60 months,15.02%,476.01,10+ years,MORTGAGE,75000.0,Oct-18,...,0.0,NaN,17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495243,24000.0,24000.0,24000.0,60 months,15.02%,571.22,10+ years,MORTGAGE,60000.0,Oct-18,...,0.0,43.0,17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495244,12000.0,12000.0,12000.0,60 months,18.94%,310.90,6 years,RENT,128000.0,Oct-18,...,0.0,46.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495245,5000.0,5000.0,5000.0,36 months,15.02%,173.38,10+ years,MORTGAGE,35000.0,Oct-18,...,2.0,15.0,7.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495246,17500.0,17500.0,17500.0,60 months,22.35%,486.82,NaN,RENT,25000.0,Oct-18,...,0.0,NaN,6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495247,20000.0,20000.0,20000.0,36 months,11.55%,660.00,10+ years,OWN,45000.0,Oct-18,...,0.0,41.0,8.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495248,5000.0,5000.0,5000.0,36 months,16.14%,176.14,NaN,OWN,9200.0,Oct-18,...,0.0,NaN,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495249,20000.0,20000.0,20000.0,60 months,15.02%,476.01,10+ years,MORTGAGE,80000.0,Oct-18,...,0.0,NaN,8.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495250,5000.0,5000.0,5000.0,36 months,16.14%,176.14,3 years,MORTGAGE,46400.0,Oct-18,...,0.0,29.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495251,22000.0,22000.0,22000.0,60 months,7.84%,444.40,10+ years,MORTGAGE,55000.0,Oct-18,...,0.0,NaN,8.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495252,5600.0,5600.0,5600.0,36 months,13.56%,190.21,NaN,RENT,15600.0,Oct-18,...,0.0,NaN,9.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495253,23000.0,23000.0,23000.0,36 months,15.02%,797.53,10+ years,MORTGAGE,75000.0,Oct-18,...,1.0,22.0,12.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495254,10000.0,10000.0,10000.0,36 months,15.02%,346.76,5 years,MORTGAGE,38000.0,Oct-18,...,3.0,6.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495255,5000.0,5000.0,5000.0,36 months,13.56%,169.83,10+ years,MORTGAGE,35360.0,Oct-18,...,1.0,21.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495256,10000.0,10000.0,9750.0,36 months,11.06%,327.68,NaN,RENT,44400.0,Oct-18,...,0.0,40.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495257,10000.0,10000.0,10000.0,36 months,16.91%,356.08,2 years,RENT,80000.0,Oct-18,...,1.0,14.0,17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
495258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/1/2018,...,NaN,NaN,NaN,NaN,10.950000,15.420000,8.920000,13.540000,13.540000,0.0
495259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2/1/2018,...,NaN,NaN,NaN,NaN,13.050000,50.299999,12.500000,19.850000,19.850000,0.0
495260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/1/2018,...,NaN,NaN,NaN,NaN,19.959999,26.219999,13.310000,19.969999,19.969999,0.0
495261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/1/2018,...,NaN,NaN,NaN,NaN,21.070000,25.719999,14.570000,15.930000,15.930000,0.0
495262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5/1/2018,...,NaN,NaN,NaN,NaN,16.000000,18.780001,10.910000,15.430000,15.430000,0.0
495263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6/1/2018,...,NaN,NaN,NaN,NaN,14.920000,19.610001,11.220000,16.090000,16.090000,0.0
495264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/1/2018,...,NaN,NaN,NaN,NaN,17.700001,18.080000,11.440000,12.830000,12.830000,0.0
495265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8/1/2018,...,NaN,NaN,NaN,NaN,13.090000,16.860001,10.170000,12.860000,12.860000,0.0
495266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/1/2018,...,NaN,NaN,NaN,NaN,13.130000,15.630000,11.100000,12.120000,12.120000,0.0
495267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/1/2018,...,NaN,NaN,NaN,NaN,11.990000,28.840000,11.340000,21.230000,21.230000,0.0
495268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/1/2018,...,NaN,NaN,NaN,NaN,20.959999,23.809999,16.090000,18.070000,18.070000,0.0
495269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/1/2018,...,NaN,NaN,NaN,NaN,16.040001,36.200001,15.940000,25.420000,25.420000,0.0
495270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/1/2019,...,NaN,NaN,NaN,NaN,27.540001,28.530001,16.540001,16.570000,16.570000,0.0